= deploy-dotfiles.sh
:toc: preamble

Simplified multi-platform dotfile management.

(WORK IN PROGRESS)

== Installation
.External dependencies
. `bash >=4.2`
. `gawk`
. `sed`

.Other dependencies
. `@hre-utils/mk-conf.sh`

.Install
[source,bash]
----
# Assuming an ubuntu system...

#  1. Install general deps:
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install gawk sed

#  2. Install script deps:
git clone https://github.com/hre-utils/mk-conf
chmod +x ./mk-conf/mk-conf.sh
mv ./mk-conf/mk-conf.sh /usr/local/bin

#  3. Install this script:
git clone https://github.com/hre-utils/deploy-dotfiles
chmod +x ./deploy-dotfiles/deploy-dotfiles.sh
mv ./deploy-dotfiles/deploy-dotfiles.sh /usr/local/bin
----


== Usage
[source]
----
USAGE: ./deploy-dotfiles.sh [OPTION] [COMMAND]

Options:
   -h | --help              show this message and exit
   -b | --build-only        compile output to 'dist/', do not deploy to
   -d | --debug LOW[,HIGH]  set debug level range

Commands:
   -c | --clean NUMBER      purges ./dist, maintaining NUMBER entries
   -n | --new PATH          inits new base directory, copying PATH if exists
----

.Terms
base (file)::
   The contents of a configuration file, containing regular text, and key:value pairs substituted during compilation.
   Located at `files/$NAME/base`.

base (section)::
   The leading section of a local configuration file, specifying per-directory options.

global config::
   Configuration settings set for compilation & deployment.
   It is  loaded prior to per-directory local options.
   Located at `config.cfg`

local config::
   Per-directory configuration file.
   It is loaded after global options, thus you may override a global default for a single file.
   Located at `files/$NAME/config.cfg`. 

.cfg (format)::
   A file format commonly used for config files.
   Characterized by bracket enclosed headings, and use of multiple brackets to denote sub-heading levels.
   Mine may be parsed non-traditionally, see https://github.com/hre-utils/mk-conf[@hre-utils/mk-conf] for more info.

=== Example(s)
Below are a list of options assuming we're adding & deploying a `.vimrc` file, located at `$HOME/.vimrc`.

==== Adding a new file
==== Deploying files
==== Building only
==== Pruning dist/


== Features
=== Safety
Decent error checking.

Sane defaults.

It should be difficult for one to accidentally nuke a config file.
If an existing dotfile is found at the deployment location, it is backed up via one of several methods:

. In-place: given `.bak` suffix
. Moved:    re-located to the `backup` directory, renamed to last modification time
. Removed:  `rm -i` to provide confirmation & interactively remove

Should the user choose to not back up a potentially overwritten file, the default copy command is `cp -i`.
The user has plenty of opportunity to prevent data loss, unless they specifically choose not to.


=== Portability
Very few dependencies.

Aside from a couple bash scripts you can easily clone, you'll probably have everything installed already.
Anyone with bash >=4.2 and gawk/sed should be set.
You don't have to download the entirety of Python3, or nonsense ruby gems.

You're welcome.


== "But why?"
Bash == best.

Using the language for things it was unequivocally not intended is a wonderful way to gain a deeper understanding of it.
No one in their right mind would make a lexer in bash... so I had to.

It also keeps the footprint & dependencies small, which make it portable.


== To Do

* [x] Diff previously generated files.
      If there's no differences, no need to compile them again.
      Best way to do this might be a dotfile within each ./dist/$WDIR with a md5sum of the base file, and the filename it's created.
      Before running, we md5sum the 'base' file, grep the list to see if there's an existing entry.

* [x] Make consistent global variables for common paths.
      The names should be straightforward, memorable, and obviously distinct to which directory they refer.

* [ ] CLI options:
    ** [x] `--new` Automatically create the requisite directory structure
    ** [x] `--clean` Remove >3 files from each dir in ./dist.
    ** [ ] `--find` Echo path to the 'base` of a specified search term

* [ ] Reporting.
      Compile information during the run into a final report.
      Use a trap to ensure the report is actually written on exits or failure.
      Report should contain: 1) exit status, 2) run summary, 3) operations performed, 4) errors encountered.
      Use `less -r` to show with color escapes enabled.

* [ ] Easier option for files that don't have any processing required.
      If it it something that's as simple as a 'cp' with no variables.

* [ ] Re-work type :multiline and :text in mk-conf, such that we can specify longer sections of text to drop in.
      Though specifying files in ./files/$WDIR/additions/ may be a more elegant solution for long additions, 4-5 line chunks seem best via a :multiline entry.

* [ ] Tokenize new text that's entered from the config.cfg file, such that we can properly strip newlines.

* [ ] Clean up terminology.
      We're referring to 'base' in like 3 different ways.
      As with variables, things should have one (and only one) clear name.

* [ ] Create deployment script, move data to XDG_DATA_HOME or .local/share

* [ ] Add `write` function. Similar to `debug`.
      For writing necessary output to the terminal.
      Will need to be quieted by '-q|--quiet'.
